In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

!pip install tqdm
from tqdm import tqdm_notebook as tqdm





In [35]:
from keras.models import Model
from keras.layers import Input, Activation,Dense,RepeatVector,Permute,Lambda,SpatialDropout1D,multiply, Concatenate, Dropout, Embedding, Conv1D,GlobalMaxPooling1D, Flatten ,MaxPooling1D, GlobalAvgPool1D,BatchNormalization
#EMBEDDING_DIM = 25
from keras import backend as K

EMBEDDING_DIM = 50
word_index=100
max_len=5
vocab_size=word_index
#vocab_size=899999
#
#



a = Input(shape=(max_len,))
x = Embedding(vocab_size, EMBEDDING_DIM)(a)
b1= Dropout(0.5)(x,training=True)
#out= Dense(15, activation='softmax')(b1)
model = Model(inputs=a, outputs=b1)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])




print('Summary of the built model...')
print(model.summary())



Summary of the built model...
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_11 (InputLayer)        (None, 5)                 0         
_________________________________________________________________
embedding_11 (Embedding)     (None, 5, 50)             5000      
_________________________________________________________________
dropout_11 (Dropout)         (None, 5, 50)             0         
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________
None


In [36]:
testseq=np.array([5,19,21,4,5])
testseq=np.expand_dims(testseq,axis=0)
testseq.shape

(1, 5)

In [37]:
model.predict(testseq)### dropout random dim for every word

array([[[ 0.02935059, -0.0655386 , -0.00304959, -0.0820678 ,
         -0.04016483, -0.        ,  0.00765166,  0.05864883,
          0.        ,  0.07843233,  0.09957042, -0.09765065,
          0.06645498,  0.05456755,  0.05794091,  0.        ,
          0.        , -0.05023823, -0.        ,  0.        ,
         -0.04370644, -0.        , -0.        , -0.        ,
         -0.07408814,  0.0769804 , -0.        ,  0.00500302,
         -0.        , -0.07050109,  0.02524874,  0.06231064,
         -0.        , -0.02076216,  0.        , -0.        ,
         -0.01174545, -0.        ,  0.        , -0.        ,
         -0.07989578, -0.05111156, -0.01164367, -0.        ,
         -0.        ,  0.01521406,  0.01451113,  0.074601  ,
          0.06767235,  0.        ],
        [-0.        , -0.        , -0.0729892 , -0.        ,
          0.0682862 , -0.04103761,  0.        ,  0.        ,
         -0.        , -0.04953165, -0.05160744, -0.06910598,
          0.09080733,  0.0517798 , -0.03887634, -

In [55]:
from keras.models import Model
from keras.layers import Input, Activation,Dense,RepeatVector,Permute,Lambda,SpatialDropout1D,multiply, Concatenate, Dropout, Embedding, Conv1D,GlobalMaxPooling1D, Flatten ,MaxPooling1D, GlobalAvgPool1D,BatchNormalization
#EMBEDDING_DIM = 25
from keras import backend as K

EMBEDDING_DIM = 50
word_index=100
max_len=5
vocab_size=word_index
#vocab_size=899999
#
#



a = Input(shape=(max_len,))
x = Embedding(vocab_size, EMBEDDING_DIM)(a)
b1= SpatialDropout1D(0.5)(x,training=True)
#out= Dense(15, activation='softmax')(b1)
model = Model(inputs=a, outputs=b1)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])




print('Summary of the built model...')
print(model.summary())



Summary of the built model...
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_19 (InputLayer)        (None, 5)                 0         
_________________________________________________________________
embedding_19 (Embedding)     (None, 5, 50)             5000      
_________________________________________________________________
spatial_dropout1d_5 (Spatial (None, 5, 50)             0         
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________
None


In [56]:
testseq=np.array([5,19,21,4,5])
testseq=np.expand_dims(testseq,axis=0)
testseq.shape

(1, 5)

In [57]:
np.round(model.predict(testseq),10)### dropout alsways same dim for every word

array([[[-0.09888957, -0.05011601,  0.06946423, -0.        ,
         -0.0478812 , -0.04922638, -0.06934235, -0.00950596,
          0.        , -0.06383459,  0.        ,  0.        ,
         -0.        , -0.        ,  0.        , -0.06073535,
         -0.07352469, -0.        ,  0.02084033,  0.        ,
          0.05813644, -0.        ,  0.08254982, -0.        ,
         -0.09732921,  0.02401636,  0.04400039, -0.05034044,
          0.0233411 , -0.00933423,  0.        , -0.        ,
          0.01211102,  0.02125838,  0.00114415, -0.00576691,
          0.        ,  0.04411326,  0.05909744,  0.        ,
          0.        , -0.        , -0.0315157 ,  0.        ,
         -0.        , -0.        , -0.00505529,  0.01786246,
          0.05755208,  0.09003895],
        [-0.02984195,  0.01247153,  0.03177883,  0.        ,
         -0.0287112 , -0.02997501,  0.08107729,  0.05591104,
          0.        ,  0.03352533,  0.        ,  0.        ,
         -0.        ,  0.        ,  0.        , -

In [101]:
from keras.models import Model
from keras.layers import Input, Activation,Dense,RepeatVector,Permute,Lambda,SpatialDropout1D,multiply, Concatenate, Dropout, Embedding, Conv1D,GlobalMaxPooling1D, Flatten ,MaxPooling1D, GlobalAvgPool1D,BatchNormalization
#EMBEDDING_DIM = 25
from keras import backend as K

EMBEDDING_DIM = 50
word_index=100
max_len=5
vocab_size=word_index
#vocab_size=899999
#
#



a = Input(shape=(max_len,))
a1= Dropout(0.99)(a,training=True)
x = Embedding(vocab_size+1, EMBEDDING_DIM)(a1)
#b1= SpatialDropout1D(0.5)(x,training=True)
#out= Dense(15, activation='softmax')(b1)
model = Model(inputs=a, outputs=x)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])




print('Summary of the built model...')
print(model.summary())



W0717 08:33:11.076184 140063519668096 nn_ops.py:4224] Large dropout rate: 0.99 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended.


Summary of the built model...
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_35 (InputLayer)        (None, 5)                 0         
_________________________________________________________________
dropout_26 (Dropout)         (None, 5)                 0         
_________________________________________________________________
embedding_30 (Embedding)     (None, 5, 50)             5050      
Total params: 5,050
Trainable params: 5,050
Non-trainable params: 0
_________________________________________________________________
None


In [102]:
testseq=np.array([5,19,21,4,5])
testseq=np.expand_dims(testseq,axis=0)
testseq.shape

(1, 5)

In [103]:
np.round(model.predict(testseq),10)### dropout entire words so they will get embeded into the zero emv which mean no "word", same as padded values

array([[[-0.0498526 ,  0.04098625,  0.02621908, -0.00907226,
         -0.04208113,  0.04791751, -0.00604559,  0.01061754,
          0.04684165, -0.0373794 , -0.01383855,  0.04947985,
         -0.00774201, -0.03742703, -0.01366746,  0.03107513,
          0.04727856,  0.04942063,  0.04497379,  0.0456886 ,
         -0.03045985, -0.00958824,  0.00659988,  0.03145171,
          0.03841816, -0.04362762,  0.04773254,  0.04471997,
          0.02733273,  0.01417663,  0.01988235, -0.0068737 ,
          0.03105542, -0.04371386, -0.04041026, -0.02718751,
         -0.0486551 , -0.01497795, -0.02060671,  0.01000934,
         -0.01002468, -0.03475279, -0.01961537,  0.03150955,
          0.04816509, -0.00308361, -0.00108596,  0.02490118,
          0.01285899,  0.01536772],
        [-0.0498526 ,  0.04098625,  0.02621908, -0.00907226,
         -0.04208113,  0.04791751, -0.00604559,  0.01061754,
          0.04684165, -0.0373794 , -0.01383855,  0.04947985,
         -0.00774201, -0.03742703, -0.01366746,  